// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var discount = 0.05;

var total = 7 * 14.50;

var afterDiscount = total * (1.0 - discount);

console.log("\xd0\xa6\xd0\xb5\xd0\xbd\xd0\xb0 \xd0\xb1\xd0\xb5\xd0\xb7 \xd1\x81\xd0\xba\xd0\xb8\xd0\xb4\xd0\xba\xd0\xb8: " + (total.toString() + " \xd0\xa0\xd1\x83\xd0\xb1"));

console.log("\xd0\xa6\xd0\xb5\xd0\xbd\xd0\xb0 \xd0\xb1\xd0\xb5\xd0\xb7 \xd1\x81\xd0\xba\xd0\xb8\xd0\xb4\xd0\xba\xd0\xb8: " + (afterDiscount.toString() + " \xd0\xa0\xd1\x83\xd0\xb1"));

var qty = 7;

var price = 14.50;

exports.qty = qty;
exports.price = price;
exports.discount = discount;
exports.total = total;
exports.afterDiscount = afterDiscount;
/*  Not a pure module */
