// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var discount = 0.05;

var total = 7 * 14.50;

var afterDiscount = total * (1.0 - discount);

console.log("Price before discount: $" + (total.toString() + "."));

console.log("Price after discount: $" + (afterDiscount.toString() + "."));

var qty = 7;

var price = 14.50;

exports.qty = qty;
exports.price = price;
exports.discount = discount;
exports.total = total;
exports.afterDiscount = afterDiscount;
/*  Not a pure module */
