// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var poem = "Я из лесу вышел,\n  был сильный мороз;\nГляжу поднимается медленно в гору ... ";

console.log(poem);

exports.poem = poem;
/*  Not a pure module */
