// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var total = 105;

console.log("The Total price is $", total);

var qty = 7;

var price = 15;

exports.qty = qty;
exports.price = price;
exports.total = total;
/*  Not a pure module */
