// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var windChill = 13.12 + 0.6215 * 5 - 11.37 * Math.pow(20, 0.16) + 0.3965 * 5 * Math.pow(20, 0.16);

console.log("At temperatyre " + 5 + " degrees C and wind speed " + 20 + " km/hr, the wind chill temperatyre is " + windChill + ". ");

var tmprt = 5;

var velocity = 20;

exports.tmprt = tmprt;
exports.velocity = velocity;
exports.windChill = windChill;
/* windChill Not a pure module */
